# Generated by Django 3.0.5 on 2020-04-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, unique=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
